name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
    paths:
      - 'private/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Wrangler
        run: npm install -g wrangler
      - name: Deploy main worker to Cloudflare Workers
        run: |
          cd private
          wrangler deploy main.js
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
