name = "scribblit-production"
main = "main.js"
compatibility_date = "2025-07-01"

[[d1_databases]]
binding = "DB"
database_name = "scribblit"
database_id = "f9c0de3c-de14-45f6-acc1-3563e63fd84e"

route = "app.scribbl.it/login"
zone_id = "f7ff3b69f5d8a4fd2a1b7af116001e44"