name = "scribblit-server"
main = "main.js"
compatibility_date = "2024-09-30"

# make AI available at env.AI.run
[ai]
binding = "AI"

[observability]
enabled = true
head_sampling_rate = 1

[limits]
cpu_ms = 100 # limit to 100 cpu ms. 3-6 is normal, 100 means something weird is happening