name = "scribblit-legacy-server"
main = "legacy_prompt.js"
compatibility_date = "2025-03-01"

# make AI available at env.AI.run
[ai]
binding = "AI"

[observability]
enabled = true
head_sampling_rate = 1