name: cron-runner-a5f0a140

on:
  schedule: # remember these are in UTC! so they don't necessarily line up with local time
      - cron: '13 22 21 7 *'
      - cron: '17 22 21 7 *'
      - cron: '27 22 21 7 *'
      - cron: '31 0 22 7 *'
      - cron: '0 9 22 7 *'
      - cron: '30 10 22 7 *'
      - cron: '0 12 22 7 *'
      - cron: '30 12 22 7 *'
      - cron: '45 12 22 7 *'
      - cron: '0 13 22 7 *'
      - cron: '15 13 22 7 *'
      - cron: '20 13 22 7 *'
      - cron: '55 13 22 7 *'
      - cron: '30 14 22 7 *'
      - cron: '30 17 22 7 *'
      - cron: '30 18 22 7 *'
      - cron: '30 21 22 7 *'
      - cron: '30 23 22 7 *'
      - cron: '15 0 23 7 *'
      - cron: '0 1 23 7 *'
      - cron: '15 1 23 7 *'
      - cron: '25 1 23 7 *'
      - cron: '30 10 23 7 *'
      - cron: '30 12 23 7 *'
      - cron: '0 13 23 7 *'
      - cron: '15 13 23 7 *'
      - cron: '20 13 23 7 *'
      - cron: '55 13 23 7 *'
      - cron: '45 19 23 7 *'
      - cron: '50 20 23 7 *'
      - cron: '0 1 24 7 *'
      - cron: '30 10 24 7 *'
      - cron: '30 12 24 7 *'
      - cron: '0 13 24 7 *'
      - cron: '15 13 24 7 *'
      - cron: '20 13 24 7 *'
      - cron: '55 13 24 7 *'
      - cron: '0 14 24 7 *'
      - cron: '30 19 24 7 *'
      - cron: '45 22 24 7 *'
      - cron: '0 1 25 7 *'
      - cron: '30 1 25 7 *'
      - cron: '30 10 25 7 *'
      - cron: '0 11 25 7 *'
      - cron: '30 12 25 7 *'
      - cron: '15 13 25 7 *'
      - cron: '20 13 25 7 *'
      - cron: '55 13 25 7 *'
      - cron: '45 15 25 7 *'
      - cron: '0 1 26 7 *'
      - cron: '30 10 26 7 *'
      - cron: '30 12 26 7 *'
      - cron: '15 13 26 7 *'
      - cron: '20 13 26 7 *'
      - cron: '40 13 26 7 *'
      - cron: '55 13 26 7 *'
      - cron: '0 1 27 7 *'
      - cron: '30 10 27 7 *'
      - cron: '30 12 27 7 *'
      - cron: '15 13 27 7 *'
      - cron: '20 13 27 7 *'
      - cron: '55 13 27 7 *'
      - cron: '0 23 27 7 *'
      - cron: '0 1 28 7 *'
      - cron: '45 3 28 7 *'
      - cron: '30 10 28 7 *'
      - cron: '0 12 28 7 *'
      - cron: '30 12 28 7 *'
      - cron: '15 13 28 7 *'
      - cron: '20 13 28 7 *'
      - cron: '55 13 28 7 *'
      - cron: '0 1 29 7 *'
      - cron: '30 10 29 7 *'
      - cron: '15 13 29 7 *'
      - cron: '20 13 29 7 *'
      - cron: '55 13 29 7 *'
      - cron: '0 1 30 7 *'
      - cron: '30 10 30 7 *'
      - cron: '15 13 30 7 *'
      - cron: '20 13 30 7 *'
      - cron: '55 13 30 7 *'
      - cron: '30 20 30 7 *'
      - cron: '0 1 31 7 *'
      - cron: '30 10 31 7 *'
      - cron: '15 13 31 7 *'
      - cron: '20 13 31 7 *'
      - cron: '55 13 31 7 *'
      - cron: '0 1 1 8 *'
      - cron: '0 9 1 8 *'
      - cron: '30 10 1 8 *'
      - cron: '15 13 1 8 *'
      - cron: '20 13 1 8 *'
      - cron: '55 13 1 8 *'
      - cron: '45 15 1 8 *'
      - cron: '0 1 2 8 *'
      - cron: '30 10 2 8 *'
      - cron: '15 13 2 8 *'
      - cron: '20 13 2 8 *'
      - cron: '40 13 2 8 *'
      - cron: '55 13 2 8 *'
      - cron: '0 1 3 8 *'
      - cron: '30 10 3 8 *'
      - cron: '15 13 3 8 *'
      - cron: '20 13 3 8 *'
      - cron: '55 13 3 8 *'
      - cron: '0 23 3 8 *'
      - cron: '0 1 4 8 *'
      - cron: '30 10 4 8 *'
      - cron: '15 13 4 8 *'
      - cron: '20 13 4 8 *'
      - cron: '55 13 4 8 *'
      - cron: '0 1 5 8 *'
      - cron: '30 10 5 8 *'
      - cron: '45 13 5 8 *'
      - cron: '0 1 6 8 *'
      - cron: '30 10 6 8 *'
      - cron: '0 1 7 8 *'
      - cron: '30 10 7 8 *'
      - cron: '0 1 8 8 *'
      - cron: '30 10 8 8 *'
      - cron: '45 15 8 8 *'
      - cron: '0 1 9 8 *'
      - cron: '30 10 9 8 *'
      - cron: '40 13 9 8 *'
      - cron: '0 1 10 8 *'
      - cron: '30 10 10 8 *'
      - cron: '0 23 10 8 *'
      - cron: '0 1 11 8 *'
      - cron: '30 10 11 8 *'
      - cron: '0 1 12 8 *'
      - cron: '30 10 12 8 *'
      - cron: '0 1 13 8 *'
      - cron: '30 10 13 8 *'
      - cron: '0 1 14 8 *'
      - cron: '30 10 14 8 *'
      - cron: '0 1 15 8 *'
      - cron: '30 10 15 8 *'
      - cron: '45 15 15 8 *'
      - cron: '0 1 16 8 *'
      - cron: '30 10 16 8 *'
      - cron: '40 13 16 8 *'
      - cron: '0 1 17 8 *'
      - cron: '30 10 17 8 *'
      - cron: '0 23 17 8 *'
      - cron: '0 1 18 8 *'
      - cron: '30 10 18 8 *'
      - cron: '0 1 19 8 *'
      - cron: '30 10 19 8 *'
      - cron: '0 1 20 8 *'
      - cron: '30 10 20 8 *'
      - cron: '0 1 21 8 *'
      - cron: '30 10 21 8 *'
      - cron: '45 15 22 8 *'
      - cron: '0 23 24 8 *'
      - cron: '0 11 25 8 *'
      - cron: '45 15 29 8 *'
      - cron: '0 23 31 8 *'
      - cron: '0 9 1 9 *'
      - cron: '45 13 2 9 *'
      - cron: '45 15 5 9 *'
      - cron: '0 23 7 9 *'
      - cron: '45 15 12 9 *'
      - cron: '0 23 14 9 *'
      - cron: '0 23 21 9 *'
      - cron: '0 11 25 9 *'
      - cron: '0 16 26 9 *'
      - cron: '0 23 28 9 *'
      - cron: '0 9 1 10 *'
      - cron: '0 23 5 10 *'
      - cron: '45 13 7 10 *'
      - cron: '0 23 12 10 *'
      - cron: '45 8 15 10 *'
      - cron: '0 23 19 10 *'
      - cron: '0 11 25 10 *'
      - cron: '0 23 26 10 *'
      - cron: '0 9 1 11 *'
      - cron: '0 23 2 11 *'
      - cron: '45 13 4 11 *'
      - cron: '0 23 9 11 *'
      - cron: '0 23 16 11 *'
      - cron: '0 23 23 11 *'
      - cron: '0 11 25 11 *'
      - cron: '0 23 30 11 *'
      - cron: '0 9 1 12 *'
      - cron: '45 13 2 12 *'
      - cron: '0 23 7 12 *'
      - cron: '0 23 14 12 *'
      - cron: '0 23 21 12 *'
      - cron: '0 11 25 12 *'
      - cron: '0 16 26 12 *'
      - cron: '0 23 28 12 *'
      - cron: '0 10 1 1 *'
      - cron: '0 23 4 1 *'
      - cron: '0 23 11 1 *'
      - cron: '0 23 18 1 *'
      - cron: '0 11 25 1 *'
      - cron: '0 11 25 2 *'
      - cron: '30 9 1 3 *'
      - cron: '0 11 25 3 *'
      - cron: '0 16 27 3 *'
      - cron: '0 11 25 4 *'
      - cron: '0 11 25 5 *'
      - cron: '0 11 25 6 *'
      - cron: '0 16 26 6 *'
      - cron: '45 7 20 7 *'
      - cron: '0 16 25 9 *'
      - cron: '0 16 25 12 *'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Process notifications
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          USER_EMAIL: rejwaedhrweghjfehjergw@yopmail.com
        run: |
          data_file="data/a5f0a140.txt"
          if [ ! -f "$data_file" ]; then
            echo "Data file not found: $data_file"
            exit 0
          fi
          now=$(date +%s)
          tmp_file=$(mktemp)
          while IFS= read -r line || [ -n "$line" ]; do
            unix="${line%%,*}"
            rest_after_unix="${line#*,}"
            id="${rest_after_unix%%,*}"
            rest_after_id="${rest_after_unix#*,}"
            status="${rest_after_id%%,*}"
            message="${rest_after_id#*,}"
            if [ "$status" = "UNSENT" ] && [ "$unix" -le "$now" ]; then
              escaped_message=$(echo "$message" | sed 's/\/\\/g' | sed 's/"/\"/g')
              json_payload=$(printf '{"personalizations":[{"to":[{"email":"%s"}],"subject":"%s"}],"from":{"email":"noreply@scribbl.it"},"content":[{"type":"text/plain","value":"%s"}]}' "$USER_EMAIL" "$escaped_message" "$escaped_message")
              curl -s -X POST https://api.sendgrid.com/v3/mail/send \
                -H "Authorization: Bearer $SENDGRID_API_KEY" \
                -H "Content-Type: application/json" \
                -d "$json_payload"
              echo "$unix,$id,SENT,$message" >> "$tmp_file"
            else
              echo "$line" >> "$tmp_file"
            fi
          done < "$data_file"
          mv "$tmp_file" "$data_file"

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/a5f0a140.txt
          if git diff --cached --quiet; then
            echo "No updates to commit"
          else
            git commit -m "ci: update notifications for a5f0a140"
            git push origin main
          fi
