name: Deploy to Cloudflare

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'private/**'
      - 'legacy_private/**'
      - 'public_v2/**'
      - 'private_v2/**'
      - 'browser_complete/**'
      - '.github/workflows/deploy_workers.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      contents: read
    name: Deploy
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Deploy Scribblit server worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'private_v2/server'
          secrets: |
            SENDGRID_API_KEY
            SECRET_KEY
            GOOGLE_CLIENT_ID
            GOOGLE_CLIENT_SECRET
            CEREBRAS_API_KEY
            XAI_API_KEY
            GEMINI_API_KEY
            GROQ_API_KEY
            ANTHROPIC_API_KEY
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          CEREBRAS_API_KEY: ${{ secrets.CEREBRAS_API_KEY }}
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

      - name: Deploy Browser Complete server worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'browser_complete/private/server'
          secrets: |
            SENDGRID_API_KEY
            SECRET_KEY
            GOOGLE_CLIENT_ID
            GOOGLE_CLIENT_SECRET
            CEREBRAS_API_KEY
            XAI_API_KEY
            GEMINI_API_KEY
            GROQ_API_KEY
            ANTHROPIC_API_KEY
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          CEREBRAS_API_KEY: ${{ secrets.CEREBRAS_API_KEY }}
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

      - name: Deploy Scribblit Stripe worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'private_v2/stripe'
          secrets: |
            STRIPE_SECRET_KEY
            STRIPE_PUBLISHABLE_KEY
            STRIPE_WEBHOOK_SECRET
            STRIPE_TEST_SECRET_KEY
            STRIPE_TEST_PUBLISHABLE_KEY
        env:
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }} # this doesn't need to be a secret but it's convenient to have it here
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
          STRIPE_TEST_SECRET_KEY: ${{ secrets.STRIPE_TEST_SECRET_KEY }}
          STRIPE_TEST_PUBLISHABLE_KEY: ${{ secrets.STRIPE_TEST_PUBLISHABLE_KEY }}
            
      - name: Minify JS files for frontend
        run: |
          npm install terser
          find public_v2 -name "*.js" ! -name "*.min.js" -exec npx terser {} -c -m -o {} \;

      - name: Deploy pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'scribblit2'
          directory: 'public_v2'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      #- name: Deploy legacy worker
      #  uses: cloudflare/wrangler-action@v3
      #  with:
      #    apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      #    accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      #    workingDirectory: 'legacy_private'