name: Deploy to Cloudflare

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'private/**'
      - 'legacy_private/**'
      - 'public_v2/**'
      - 'private_v2/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      contents: read
    name: Deploy
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy legacy worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'legacy_private'
          
      - name: Deploy private_v2 Worker (with secret)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'private_v2'
          secrets: |
            SENDGRID_API_KEY
            SECRET_KEY
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
      
      - name: Deploy Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'scribblit2'
          directory: 'public_v2'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}