# .github/workflows/TEST.yml
name: Every‑4‑Minutes Test

on:
  schedule:
    - cron: '*/4 * * * *'    # “every 4th minute” in UTC
  workflow_dispatch:         # lets you also click “Run workflow” manually

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Timestamp
        run: echo "⏰ This ran at $(date -u) UTC ($(date))"
