name: handle-generate-workflow

on:
  repository_dispatch:
    types: [generate_workflow]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Write workflow file
        run: |
          mkdir -p "$(dirname "${{ github.event.client_payload.workflowFileName }}")"
          cat << 'EOF' > "${{ github.event.client_payload.workflowFileName }}"
          ${{ github.event.client_payload.workflowYml }}
          EOF

      - name: Write data file
        run: |
          mkdir -p "$(dirname "${{ github.event.client_payload.dataFileName }}")"
          cat << 'EOF' > "${{ github.event.client_payload.dataFileName }}"
          ${{ github.event.client_payload.dataFileContent }}
          EOF

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "${{ github.event.client_payload.workflowFileName }}" "${{ github.event.client_payload.dataFileName }}"
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "ci: update workflow and data for ${{ github.event.client_payload.dataFileName }}"
            git push origin HEAD:main
          fi